# Generated by Django 4.1 on 2024-02-05 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "verbose_name": "Лента новостей",
                "verbose_name_plural": "Ленты новостей",
            },
        ),
    ]
